apiVersion: v1
kind: Pod
metadata:
  name: my-pod-memory
spec:
  containers:
  - name: my-pod-memory-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
