apiVersion: v1
kind: Namespace
metadata:
  name: pda-hoteles
  labels:
    module: pda-hoteles
    namespace: pda-hoteles
---
apiVersion: v1
kind: ConfigMap
metadata:
        name: config-map-hoteles-pda
        namespace: pda-hoteles
data:
        DB_PATH: "/db/hotels.json"
        DB_TABLE: "hotels"
