---
apiVersion: v1
kind: Namespace
metadata:
    name: hotel
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel
  namespace: hotel
  labels:
    app: hotel
    module: booking
    tier: backend
    type: app
    release: v3
data:
  DB_PATH: /db/hotels.json
  DB_TABLE: hotels
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hotel
    namespace: hotel
    labels:
        app: hotel
        module: booking
        tier: backend
        type: app
        release: v3
spec:
    replicas: 3
    selector:
        matchLabels:
            app: hotel
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    template:
        metadata:
            labels:
                app: hotel
                module: booking
                tier: backend
                type: app
                release: v3
        spec:
            containers:
                - name: hotel
                  image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
                  ports:
                    - containerPort: 5000
                  livenessProbe:
                    tcpSocket:
                        port: 5000
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    timeoutSeconds: 5
                    failureThreshold: 3
                    successThreshold: 1
                  readinessProbe:
                    httpGet:
                        path: /status
                        port: 5000
                    initialDelaySeconds: 5
                    periodSeconds: 5
                    timeoutSeconds: 5
                    failureThreshold: 2
                    successThreshold: 2
                  envFrom:
                    - configMapRef:
                        name: hotel