apiVersion: v1
kind: Namespace
metadata:
    name: hotels-prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hotels-config-env
  namespace: hotels-prod
  labels:
    app: hotels
    appType: API
    tier: backend
    module: booking-rooms
    release: v3-slim
data:
  DB_PATH: "/db/hotels.json"
  DB_TABLE: "hotels"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hotels
    namespace: hotels-prod
    labels:
      app: hotels
      appType: API
      tier: backend
      module: booking-rooms
      release: v3-slim
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: hotels
      release: v3-slim
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hotels
        appType: API
        tier: backend
        module: booking-rooms
        release: v3-slim
    spec:
      containers:
        - name: hotels
          image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1            
          envFrom:
            - configMapRef:
                name: hotels-config-env
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "0.5"         
            