---
apiVersion: v1
kind: Namespace
metadata: 
  name: reservas-monolith-u4
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-unidad4
  namespace: reservas-monolith-u4
  labels:
    tier: monolith
    module: reservas
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: monolith
      module: reservas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%
      maxSurge: 1
  template:
    metadata:
      labels:
         tier: monolith
         module: reservas
         release: monolith_v2
    spec:
      containers:
      - name: reservas
        image: ghcr.io/go-elevate/k8s4arch-hotels:monolith-v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20        
        readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10