---
apiVersion: v1
kind: Namespace
metadata:
    name: hotel
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hotel
    namespace: hotel
    labels:
        app: hotel
        module: booking
        tier: monolith
        type: app
        release: v2
spec:
    replicas: 3
    selector:
        matchLabels:
            app: hotel
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    template:
        metadata:
            labels:
                app: hotel
                module: booking
                tier: monolith
                type: app
                release: v2
        spec:
            containers:
                - name: hotel
                  image: ghcr.io/go-elevate/k8s4arch-hotels:monolith-v2
                  ports:
                    - containerPort: 80
                  livenessProbe:
                    tcpSocket:
                        port: 80
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    timeoutSeconds: 5
                    failureThreshold: 3
                    successThreshold: 1
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 80
                    initialDelaySeconds: 5
                    periodSeconds: 5
                    timeoutSeconds: 5
                    failureThreshold: 2
                    successThreshold: 2