apiVersion: v1
kind: Namespace
metadata:
    name: hotels-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hotels
    namespace: hotels-prod
    labels:
      app: hotels
      appType: webApp
      tier: monolith
      module: booking-rooms
      release: v2
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: hotels
      release: v2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hotels
        appType: webApp
        tier: monolith
        module: booking-rooms
        release: v2
    spec:
      containers:
        - name: hotels
          image: ghcr.io/go-elevate/k8s4arch-hotels:monolith-v2
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 3
