apiVersion: apps/v1
kind: Deployment
metadata:
    name: pda-deployment
    labels:
        app: demo
spec:
    replicas: 3
    selector:
        matchLabels:
            app: demo
    template:
        metadata:
            name: demo-app
            labels:
                app: demo
        spec:
            containers:
            - name: demo
              image: 'ingenia/hello-kubernetes:1.9'
              ports:
              - containerPort: 8080