apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hoteles-backend
  namespace: practica8
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G