apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoteles-back-front
  namespace: nmspc-hoteles
  labels:
    app: hoteles-back-front
    module: hoteles
    type: web
    release: slim
    tier: backend-frontend
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: hoteles-back-front
      module: hoteles
      release: slim
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hoteles-back-front
        module: hoteles
        type: web
        release: slim
        tier: backend-frontend
    spec:
      initContainers:
      - name: hoteles-migrations
        image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
        command: ["python", "migrations.py"]
        envFrom:
        - configMapRef:
            name: hoteles-backend-cm
        volumeMounts:
        - name: db-volume
          mountPath: /db
      containers:
      - name: hoteles-backend
        image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: hoteles-backend-cm
        volumeMounts:
        - name: db-volume
          mountPath: /db
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 10
          failureThreshold: 1
          successThreshold: 1
        readinessProbe:
          httpGet:
            port: 5000
            path: /status
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
          successThreshold: 1
        resources:
          requests:
            cpu: "0.2"
            memory: "100Mi"
          limits:
            cpu: "1"
            memory: "200Mi"
      - name: hoteles-frontend
        image: ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 10
          failureThreshold: 1
          successThreshold: 1
        readinessProbe:
          httpGet:
            port: 80
            path: /
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
          successThreshold: 1
        resources:
          requests:
            cpu: "0.2"
            memory: "100Mi"
          limits:
            cpu: "1"
            memory: "200Mi"
      volumes:
      - name: db-volume
        emptyDir: {}
