apiVersion: v1
kind: Namespace
metadata:
  name: pda-hoteles
  labels:
    module: pda-hoteles
---
apiVersion: v1
kind: Secret
metadata:  
    name: db-data
type: Opaque
data:  
    DB_PATH: L2RiL2hvdGVscy5qc29u
    DB_TABLE: aG90ZWxz
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: pda-hotel-back-slimv1
    namespace: pda-hoteles
    labels:
        app: pda-dep-back-slimv1
        owner: aws-pda
        type: web
        ejercicio: unidad6
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pda-dep-back-slimv1
            owner: pda-aws
            type: web
            ejercicio: unidad6
    strategy:
            type: RollingUpdate
            rollingUpdate:
                    maxUnavailable: 25%
                    maxSurge: 2
    template:
        metadata:
            name: pda-dep-back-slimv1-pods
            labels:
                app: pda-dep-back-slimv1
                owner: pda-aws
                type: web
                ejercicio: unidad6
        spec:
            initContainers:
            - name: pda-dep-back-slimv1-init
              image: 'ghcr.io/go-elevate/k8s4arch-hotels-backend:slim'
              command: ["python"]
              args: ["migrations.py"]
              envFrom:
              - secretRef:
                    name: db-data
              volumeMounts:
                      - name: db-volume
                        mountPath: /db
              ports:
                      - containerPort: 5000
            containers:
            - name: pda-dep-back-slimv1-cont
              image: 'ghcr.io/go-elevate/k8s4arch-hotels-backend:slim'
              envFrom:
              volumeMounts:
                      - name: db-volume
                        mountPath: /db
              ports:
                      - containerPort: 80
            - name: pda-dep-front-slimv1-cont
              image: 'ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim'
            volumes:
            - name: db-volume
              emptyDir: {}
