apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-hotels
  namespace: practica6
  labels:
    app: booking-hotels
    modulo: reservas
    capa: backend-frontend
    version: slim
    tecnologia: python-react
    ambiente: prod
spec:
  selector:
    matchLabels:
      app: booking-hotels
      modulo: reservas
      capa: backend-frontend
      version: slim
      tecnologia: python-react
      ambiente: prod
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: booking-hotels
        modulo: reservas
        capa: backend-frontend
        version: slim
        tecnologia: python-react
        ambiente: prod
    spec:
      initContainers:
      - name: hoteles-migrations
        image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
        command: ["python", "migrations.py"]
        envFrom:
          - configMapRef:
              name: hoteles-config-map
        volumeMounts:
          - name: database-data
            mountPath: /db
      containers:
      - name: hoteles-backend
        image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  5000
        envFrom:
          - configMapRef:
              name: hoteles-config-map
        volumeMounts:
          - name: database-data
            mountPath: /db
        resources:
          limits:
            cpu: "1"
            memory: "2G"
          requests:
            cpu: "0.5"
            memory: "1G"
      - name: hoteles-frontend
        image: ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
      volumes:
      - name: database-data
        emptyDir: {}
