apiVersion: v1 
kind: ConfigMap 
metadata: 
        name: config-map-hoteles-pda 
        namespace: pda-hoteles 
data: 
#       hoteles.db_path: "/db/hotels.json" 
        hoteles.db_table: "hotels" 
        otra.variable: "no la usa el deployment" 
---
apiVersion: v1
kind: Secret
metadata:
   name: secret-hoteles-pda
   namespace: pda-hoteles
type: Opaque
data:
   hoteles.db_path: L2RiL2hvdGVscy5qc29u
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: pda-hotel-back-slimv1
    namespace: pda-hoteles
    labels:
        app: pda-dep-back-slimv1
        owner: aws-pda
        type: web
        ejercicio: unidad6
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pda-dep-back-slimv1
            owner: pda-aws
            type: web
            ejercicio: unidad6
    strategy:
            type: RollingUpdate
            rollingUpdate:
                    maxUnavailable: 25%
                    maxSurge: 2
    template:
        metadata:
            name: pda-dep-back-slimv1-pods
            labels:
                app: pda-dep-back-slimv1
                owner: pda-aws
                type: web
                ejercicio: unidad6
        spec:
            containers:
            - name: pda-dep-back-slimv1-mig
              image: 'ghcr.io/go-elevate/k8s4arch-hotels-backend:slim'
              command: ["python"]
              args: ["migrations.py"]
              env:
                      - name: DB_PATH
                        valueFrom:
                                secretKeyRef:
                                        name: secret-hoteles-pda
                                        key: hoteles.db_path
                      - name: DB_TABLE
                        valueFrom:
                                configMapKeyRef:
                                        name: config-map-hoteles-pda
                                        key: hoteles.db_table
            - name: pda-dep-back-slimv1-app
              image: 'ghcr.io/go-elevate/k8s4arch-hotels-backend:slim'
              env:
                      - name: DB_PATH
                        valueFrom:
                                secretKeyRef:
                                        name: secret-hoteles-pda
                                        key: hoteles.db_path
                      - name: DB_TABLE
                        valueFrom:
                                configMapKeyRef:
                                        name: config-map-hoteles-pda
                                        key: hoteles.db_table
            - name: pda-dep-front-slimv1-cont
              image: 'ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim'
              ports:
                      - containerPort: 5000
              env:
                      - name: DB_PATH
                        valueFrom:
                                secretKeyRef:
                                        name: secret-hoteles-pda
                                        key: hoteles.db_path
                      - name: DB_TABLE
                        valueFrom:
                                configMapKeyRef:
                                        name: config-map-hoteles-pda
                                        key: hoteles.db_table
