apiVersion: v1
kind: Namespace
metadata:
  name: pda-hoteles
  labels:
    module: pda-hoteles
    namespace: pda-hoteles
---
apiVersion: v1
kind: ConfigMap
metadata:  
    name: db-data
    namespace: pda-hoteles
data:
  DB_PATH: "/db/hotels.json"
  DB_TABLE: "hotels"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: pda-hotel-back-slimv1
    namespace: pda-hoteles
    labels:
        app: pda-dep-back-slimv1
        owner: aws-pda
        type: web
        ejercicio: unidad6
spec:
    replicas: 2
    selector:
        matchLabels:
            app: pda-dep-back-slimv1
            owner: aws-pda
            type: web
            ejercicio: unidad6
    strategy:
            type: RollingUpdate
            rollingUpdate:
                    maxUnavailable: 25%
                    maxSurge: 2
    template:
        metadata:
            name: pda-dep-back-slimv1-pods
            labels:
                app: pda-dep-back-slimv1
                owner: aws-pda
                type: web
                ejercicio: unidad6
        spec:
            initContainers:
            - name: pda-dep-back-slimv1-init
              image: 'ghcr.io/go-elevate/k8s4arch-hotels-backend:slim'
              command: ["python"]
              args: ["migrations.py"]
              envFrom:
              - configMapRef:
                      name:  db-data
              volumeMounts:
              - name: db-volume
                mountPath: /db
            containers:
            - name: pda-dep-back-slimv1-cont
              image: 'ghcr.io/go-elevate/k8s4arch-hotels-backend:slim'
              envFrom:
              - configMapRef:
                      name:  db-data
              resources:
                  requests:
                    cpu: "0.5"
                    memory: "300Mi"
                  limits:
                    cpu: "1.5"
                    memory: "500Mi"
              volumeMounts:
              - name: db-volume
                mountPath: /db
              ports:
              - containerPort: 5000
              livenessProbe:
                  tcpSocket:
                    port: 5000
                  initialDelaySeconds: 2
                  periodSeconds: 2
                  failureThreshold: 1
                  successThreshold: 1
              readinessProbe:
                  httpGet:
                    port: 5000
                    path: /status
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  failureThreshold: 5
                  successThreshold: 2
            - name: pda-dep-front-slimv1-cont
              image: 'ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim'
              resources:
                  requests:
                    cpu: "0.2"
                    memory: "100Mi"
                  limits:
                    cpu: "0.5"
                    memory: "150Mi"
              ports:
              - containerPort: 80
              livenessProbe:
                  tcpSocket:
                    port: 80
                  initialDelaySeconds: 2
                  periodSeconds: 2
                  failureThreshold: 1
                  successThreshold: 1
              readinessProbe:
                  httpGet:
                    port: 80
                    path: /
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  failureThreshold: 5
                  successThreshold: 2
            volumes:
            - name: db-volume
              emptyDir: {}
