apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/psp: eks.privileged
    creationTimestamp: "2021-05-05T20:44:00Z"
    generateName: pda-hotel-back-slimv1-9bd9559c8-
    labels:
      app: pda-dep-back-slimv1
      ejercicio: unidad6
      owner: pda-aws
      pod-template-hash: 9bd9559c8
      type: web
    name: pda-hotel-back-slimv1-9bd9559c8-jhnhp
    namespace: pda-hoteles
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: pda-hotel-back-slimv1-9bd9559c8
      uid: 7bf78bcf-4f22-4c67-b03c-92db1be4fb9f
    resourceVersion: "509878"
    selfLink: /api/v1/namespaces/pda-hoteles/pods/pda-hotel-back-slimv1-9bd9559c8-jhnhp
    uid: e8843723-ecad-434c-b125-2e1ca5152b9d
  spec:
    containers:
    - args:
      - migrations.py
      command:
      - python
      envFrom:
      - secretRef:
          name: db-data
      image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
      imagePullPolicy: IfNotPresent
      name: pda-dep-back-slimv1-mig
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /db
        name: db-volume
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-hbjs9
        readOnly: true
    - envFrom:
      - secretRef:
          name: db-data
      image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
      imagePullPolicy: IfNotPresent
      name: pda-dep-back-slimv1-app
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /db
        name: db-volume
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-hbjs9
        readOnly: true
    - image: ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim
      imagePullPolicy: IfNotPresent
      name: pda-dep-front-slimv1-cont
      ports:
      - containerPort: 5000
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-hbjs9
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: ip-192-168-183-50.sa-east-1.compute.internal
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - emptyDir: {}
      name: db-volume
    - name: default-token-hbjs9
      secret:
        defaultMode: 420
        secretName: default-token-hbjs9
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2021-05-05T20:44:00Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2021-05-05T20:44:00Z"
      message: 'containers with unready status: [pda-dep-back-slimv1-mig]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2021-05-05T20:44:00Z"
      message: 'containers with unready status: [pda-dep-back-slimv1-mig]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2021-05-05T20:44:00Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://c1d41b6e19c13effe4831948fbf60c1696fdf28e1436075ff326c8536a9c287f
      image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
      imageID: docker-pullable://ghcr.io/go-elevate/k8s4arch-hotels-backend@sha256:a9688019bb846491b25115de2d68f78589f907e6f6a7e9632f49269139822fbb
      lastState: {}
      name: pda-dep-back-slimv1-app
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2021-05-05T20:44:01Z"
    - containerID: docker://02432e888bf4811e9467899f0676890560becbfcca861b47d87c7a4223345636
      image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
      imageID: docker-pullable://ghcr.io/go-elevate/k8s4arch-hotels-backend@sha256:a9688019bb846491b25115de2d68f78589f907e6f6a7e9632f49269139822fbb
      lastState:
        terminated:
          containerID: docker://02432e888bf4811e9467899f0676890560becbfcca861b47d87c7a4223345636
          exitCode: 0
          finishedAt: "2021-05-05T20:45:38Z"
          reason: Completed
          startedAt: "2021-05-05T20:45:37Z"
      name: pda-dep-back-slimv1-mig
      ready: false
      restartCount: 4
      started: false
      state:
        waiting:
          message: back-off 1m20s restarting failed container=pda-dep-back-slimv1-mig
            pod=pda-hotel-back-slimv1-9bd9559c8-jhnhp_pda-hoteles(e8843723-ecad-434c-b125-2e1ca5152b9d)
          reason: CrashLoopBackOff
    - containerID: docker://4cf5e80966c4d2f925d886d9aae1ed0b5bf91d7f9fa2265c634f2c4aea62527a
      image: ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim
      imageID: docker-pullable://ghcr.io/go-elevate/k8s4arch-hotels-frontend@sha256:28abe3404f6f610161697012f31db67145f8863f276b10581ec3ed5a6a6d05bb
      lastState: {}
      name: pda-dep-front-slimv1-cont
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2021-05-05T20:44:02Z"
    hostIP: 192.168.183.50
    phase: Running
    podIP: 192.168.182.188
    podIPs:
    - ip: 192.168.182.188
    qosClass: BestEffort
    startTime: "2021-05-05T20:44:00Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
