---
apiVersion: v1
kind: Namespace
metadata:
  name: hotel
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel
  namespace: hotel
  labels:
    app: hotel
    module: booking
    tier: multicontainer
    type: app
    release: v4
data:
  DB_PATH: /db/hotels.json
  DB_TABLE: hotels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel
  namespace: hotel
  labels:
    app: hotel
    module: booking
    tier: multicontainer
    type: app
    release: v4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotel
  strategy:
      type: RollingUpdate
      rollingUpdate:
          maxUnavailable: 1
          maxSurge: 2
  template:
    metadata:
      labels:
        app: hotel
        module: booking
        tier: multicontainer
        type: app
        release: v4
    spec:
      initContainers:
        - name: hotel-initial
          image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
          imagePullPolicy: Always
          command: ["python"]
          args: ["migrations.py"]
          envFrom:
            - configMapRef:
                name: hotel
          volumeMounts:
            - name:  hotel
              mountPath: /db
      containers:
        - name: hotel-frontend
          image: ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
                port: 80
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
                path: /
                port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 2
          envFrom:
            - configMapRef:
                name: hotel
          resources:
            requests:
              memory: "450Mi"
              cpu: "250m"
            limits:
              memory: "1900Mi"
              cpu: "1"
        - name: hotel-backend
          image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          livenessProbe:
            tcpSocket:
                port: 5000
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
                path: /status
                port: 5000
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 2
          envFrom:
            - configMapRef:
                name: hotel
          resources:
            requests:
              memory: "450Mi"
              cpu: "250m"
            limits:
              memory: "1900Mi"
              cpu: "1"
          volumeMounts:
            - name:  hotel
              mountPath: /db
      volumes:
        - name:  hotel
          emptyDir: {}