apiVersion: v1
kind: Namespace
metadata:
    name: hotels-prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hotels-config-env
  namespace: hotels-prod
  labels:
    app: hotels-multicontainers
    appType: web
    tier: backend
    module: booking-rooms
    release: v4
data:
  DB_PATH: "/db/hotels.json"
  DB_TABLE: "hotels"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hotels-multicontainers
    namespace: hotels-prod
    labels:
      app: hotels-multicontainers
      appType: web
      tier: backend
      module: booking-rooms
      release: v4
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: hotels-multicontainers
      release: v4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hotels-multicontainers
        appType: web
        tier: backend
        module: booking-rooms
        release: v4
    spec:
      initContainers:
      - name: migrations-data
        image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
        command: ["python", "migrations.py"]
        envFrom:
          - configMapRef:
              name: hotels-config-env        
        volumeMounts:
        - name: data-volume
          mountPath: /db 
      containers:
        - name: hotels-backend
          image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1            
          envFrom:
            - configMapRef:
                name: hotels-config-env
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "0.5"
          volumeMounts:
            - name: data-volume
              mountPath: /db              
        - name: hotels-frontend
          image: ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1            
          resources:
              limits:
                memory: "512Mi"
                cpu: "1"
              requests:
                memory: "256Mi"
                cpu: "0.5"
      volumes:
      - name: data-volume
        emptyDir: {}              