Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
  IP_NW = "192.168.56."
  MASTER_IP_START = 1
  NODE_IP_START = 2
  LB_IP_START = 30
  (1..2).each do |i|
          node.vm.provider "virtualbox" do |vb|
              vb.memory = 2048
              vb.cpus = 2
          end
      end
  end
  end
  